jwt:
  secret: ${JWT_SECRET}
  expire: ${JWT_EXPIRE}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10     # 주소를 갱신하는 시간
    lease-expiration-duration-in-seconds: 30  # 가져온 주소의 만료 시간
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: false  # 현재 자신의 IP주소를 유레카에 등록
    fetch-registry: true        # 유레카에 등록된 주소들을 받아오는 것


spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: board_command
              uri: lb://board-command
              predicates:
                - Path=/board/reg, /board/update, /board/delete

              filters:
                - JwtFilter

            - id: board_query
              uri: lb://board-query
              predicates:
                - Path=/board/list, /board/read/**

            - id: origin
              uri: http://localhost:8083
              predicates:
                - Path=/**